/* Goxel 3D voxels editor
 *
 * copyright (c) 2018 Guillaume Chereau <guillaume@noctua-software.com>
 *
 * Goxel is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.

 * Goxel is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.

 * You should have received a copy of the GNU General Public License along with
 * goxel.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "goxel.h"

#include "utils/b64.h"

#define TEST(cond) \
    do { \
        if (!(cond)) { \
            LOG_E("Test fail: %s (%s: %d)", __func__, __FILE__, __LINE__); \
            exit(-1); \
        } \
    } while(0)

static void test_file(const char *b64_data, uint32_t crc32)
{
    FILE *file;
    size_t data_size;
    uint8_t *data;
    int err;

    if (DEFINED(WIN32)) return; // Don't test on Windows for the moment!
    data = calloc(b64_decode(b64_data, NULL), 1);
    data_size = b64_decode(b64_data, data);
    file = fopen("/tmp/goxel_test.gox", "w");
    fwrite(data, data_size, 1, file);
    fclose(file);
    free(data);
    err = goxel_import_file("/tmp/goxel_test.gox", NULL);
    TEST(err == 0);
    TEST(volume_crc32(goxel.image->active_layer->volume) == crc32);
    image_delete(goxel.image);
    goxel.image = image_new();
    sys_delete_file("/tmp/goxel_test.gox");
}

static void test_load_file_v2(void)
{
    // Load a simple file.
    const char *b64_data =
        "R09YIAIAAABJTUcgAAAAAAAAAABCTDE2LAEAAIlQTkcNChoKAAAADUlIRFIA"
        "AABAAAAAQAgGAAAAqmlx3gAAAPNJREFUeF5j/A8EDAwMjAwUgO+MjP85//8n"
        "14z/A2k/E8MwABQEPgMjJAEwjFjAxDDCAROjyvf/lIYB43cVss0YaPuHRQr4"
        "z3mH7EJ8tAwY8WXAaACM9FpgNAWMpoCRHQKjLcHRMmC0DBgtA0Z0CIwWgqOF"
        "4GghOFoIjhaCIzkERmuB0VpgtBYYrQVGa4HRWmAEh8BoNThaDY5Wg6PV4Gg1"
        "OFoNjlaDIzcERtsBo+2A0XbAaDtgtB0w2g4YbQeMtgNGbAiMNoRGG0KjDaHR"
        "htBoQ2i0ITTaEBptCI02hEZqCIy2BEdbgqMtwdGW4GhLcCSHAACDDx/OAZLa"
        "WgAAAABJRU5ErkJgggAAAABMQVlSmgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAQAAABuYW1lCgAAAGJhY2tncm91bmQDAAAAbWF0QAAAAAAAgD8AAAAA"
        "AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAA"
        "AAAAAAAAAAAAgD8CAAAAaWQEAAAAAQAAAAcAAABiYXNlX2lkBAAAAAAAAAAA"
        "AAAA";
    test_file(b64_data, 0xc7c4c9ff);
}

static void test_load_file_v1_with_preview(void)
{
    // Load a simple file in v1 of goxel format, with embedded preview,
    // as generated by the mobile version 0.7.1.
    const char *b64_data =
        "R09YIAEAAABJTUcgAAAAAAAAAABQUkVWPAUAAIlQTkcNChoKAAAADUlIRFIA"
        "AACAAAAAgAgGAAAAwz5hywAABQNJREFUeF5jGAWjITAaAqMhMBoCoyEwGgKj"
        "ITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKj"
        "ITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKj"
        "ITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKj"
        "ITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKj"
        "ITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKj"
        "ITAaAqMhMDhCQIeNzT6Yi6t+ND5GYAhU8fPvP6Cl9R+EuyQl9yszMNgPx2Bg"
        "Hk3dqCGgxsRkP1dO7oG2sLACI1AKhGU4ORU8+PgSvv38yXD99++DwynMGEcT"
        "ACIEirm59/vJyztghAkjIphOvHt3YObz5w33GBiGRUIYLQGAsa0ELN5nAXO9"
        "kZiYAjjyQRGOjJFSBKg08BxGpcGITwAhvLz1TYqKC3g5ORkYYJGOpViEVQcg"
        "moWFhcFCUNBBg4XF4d6XLw/eMzA8HKolKdNIrwL+//7d8O7vX5RgQI5sGBuu"
        "AJpIOIAJhvHfPwdgADoM5TAc8Qng2Y8fDH137jAcef2agZmZmQGjUYSlOvj6"
        "5w/Dgrt3Gfa+fDnk8w8LwygAh8CWV68Yrn//zhAqLs4gyMGBNVQYgYnh2b9/"
        "DAtv3GD4O0zCbcT3AiwZGP4jxyWoURQhL8+gx8sLaQ9CJVnZ2BjWPXzIcPHt"
        "W5SoP83A4PBuCPcIRnwVwGdpiRKhoJy9FBjRix4/ZvgBbRt8BlYNfRcuYEQ+"
        "j74+w7sh3h0c8SWAj48PuAT4ePw4wx+03A2qCJxlZBgOP3mCkkjYgNUEj4EB"
        "A5uEBMPChQuHdBiOtgGgUcsPLAl+AxPAJ2BCgMX2DyBjDzDy2ZGiHxT5Qh4e"
        "DMMFjCYApJhkFRZmAFUJ327dwigNQMqE3N3BuZ5hGIERPxD09u3bA7Kysgmw"
        "OGXm4mLgkJUFc0FVAiuQxQks8vltbFAi//fv3wy7d+92+Pr168OhnB5G5wKg"
        "sWdpablfWFgYZVAHVCWwff7MIGRsjBLHL168OHDmzJkGYOIZ8vMBo3MB0Kh9"
        "8uTJQhATORGASgNeYGkAGiCCpYB79+4d2Ldvn+P3798fDoeaYDQBIMUiKEeD"
        "qgQuLi4FEAZJcQAHhUAJAFTk79q1y+H69euNDMMIjFYBOCITViXw8fExvHz5"
        "8sDevXsdGUbByAoBYHVgr6mpObokbDThj4bAaAiMhsBoCIyGwGgIjIbAaAiM"
        "hsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiM"
        "hsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiM"
        "hsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiM"
        "hsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiM"
        "hsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiM"
        "hsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyGwGgIkBgCADB4"
        "2BRvDISwAAAAAElFTkSuQmCCAAAAAEJMMTb1AAAAiVBORw0KGgoAAAANSUhE"
        "UgAAAEAAAABACAYAAACqaXHeAAAAvElEQVR4XmMYBaMhMBoCoyEwGgKjITAa"
        "AqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAaAqMhMBoCoyEwGgKjITAa"
        "AqMhMBoCoyEwGgKjITAaAqMhMBoCIz0E/kMBueFAqf7RFDgaAqMhMLAhsI+B"
        "4T8Ik+sKSvWPxv9oCIyGwGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhsBoCIyG"
        "wGgIjIbAaAiMhsBoCIyGwGgIjIbAaAiMhgCVQgAAwAEW5Yj9s+cAAAAASUVO"
        "RK5CYIIAAAAATEFZUpoAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAA"
        "bmFtZQoAAABiYWNrZ3JvdW5kAwAAAG1hdEAAAAAAAIA/AAAAAAAAAAAAAAAA"
        "AAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAA"
        "AIA/AgAAAGlkBAAAAAEAAAAHAAAAYmFzZV9pZAQAAAAAAAAAAAAAAA==";
    test_file(b64_data, 0xb5e8d973);
}

static void test_load_corrupt(void)
{
    FILE *file;
    int err;
    if (DEFINED(WIN32)) return; // Don't test on Windows for the moment!
    file = fopen("/tmp/goxel_test.gox", "w");
    fclose(file);
    err = goxel_import_file("/tmp/goxel_test.gox", NULL);
    TEST(err != 0);
    sys_delete_file("/tmp/goxel_test.gox");
}

static void test_xcom_swatches_file_roundtrip(void)
{
    int err;
    uint8_t swatches[XCOM_SWATCHES_COUNT][4];

    if (DEFINED(WIN32)) return; // Don't test on Windows for the moment!

    memcpy(goxel.image->xcom_swatches[0], (uint8_t[]){1, 2, 3, 255}, 4);
    memcpy(goxel.image->xcom_swatches[7], (uint8_t[]){250, 128, 64, 255}, 4);
    memcpy(swatches, goxel.image->xcom_swatches, sizeof(swatches));

    save_to_file(goxel.image, "/tmp/goxel_xcom_swatches.gox");
    memset(goxel.image->xcom_swatches, 0, sizeof(goxel.image->xcom_swatches));
    err = load_from_file("/tmp/goxel_xcom_swatches.gox", true);
    TEST(err == 0);
    TEST(memcmp(goxel.image->xcom_swatches, swatches, sizeof(swatches)) == 0);

    image_delete(goxel.image);
    goxel.image = image_new();
    sys_delete_file("/tmp/goxel_xcom_swatches.gox");
}

static void test_gpu_accel_safety_helpers(void)
{
    size_t result = 0;
    int dirty[2][3] = {{0, 0, 0}, {16, 0, 0}};
    int negative[1][3] = {{-16, -32, -48}};
    int halo[54][3];
    int i, count;
    bool found_negative_corner = false;

    TEST(gpu_accel_checked_mul_size(16, 4096, &result));
    TEST(result == 65536);
    TEST(!gpu_accel_checked_mul_size(SIZE_MAX, 2, &result));
    TEST(gpu_accel_checked_add_size(SIZE_MAX - 1, 1, &result));
    TEST(result == SIZE_MAX);
    TEST(!gpu_accel_checked_add_size(SIZE_MAX, 1, &result));
    TEST(!gpu_accel_checked_add_size(1, 1, NULL));
    TEST(strcmp(gpu_accel_mode_name(GPU_ACCEL_OFF), "Off") == 0);
    TEST(strcmp(gpu_accel_mode_name(GPU_ACCEL_AUTO), "Auto") == 0);
    TEST(strcmp(gpu_accel_mode_name(GPU_ACCEL_VALIDATION),
                "Validation") == 0);
    count = gpu_accel_expand_tile_halo(
            (const int (*)[3])dirty, 1, halo, 54);
    TEST(count == 27);
    count = gpu_accel_expand_tile_halo(
            (const int (*)[3])dirty, 2, halo, 54);
    TEST(count == 36);
    TEST(gpu_accel_expand_tile_halo(
            (const int (*)[3])dirty, 2, halo, 35) == -1);
    count = gpu_accel_expand_tile_halo(
            (const int (*)[3])negative, 1, halo, 54);
    TEST(count == 27);
    for (i = 0; i < count; i++)
        if (halo[i][0] == -32 && halo[i][1] == -48 &&
                halo[i][2] == -64)
            found_negative_corner = true;
    TEST(found_negative_corner);
}

static void test_gpu_marching_cubes_parity(void)
{
#ifdef __APPLE__
    volume_t *volume = volume_new();
    gpu_accel_t *accel;
    voxel_vertex_t *vertices =
        calloc(16384 * 3, sizeof(*vertices));
    const uint8_t colors[][4] = {
        {40, 120, 220, 255}, {220, 80, 40, 180},
        {70, 210, 90, 255}, {190, 80, 210, 220},
    };
    const int voxel_positions[][3] = {
        {-1, 7, 7}, {0, 7, 7}, {15, 7, 7}, {16, 7, 7},
        {7, 0, 15}, {7, 0, 16}, {7, 15, 0}, {7, 16, 0},
    };
    const int tile_positions[][3] = {
        {-16, 0, 0}, {0, 0, 0}, {16, 0, 0},
        {0, 0, 16}, {0, 16, 0},
    };
    int count, size, subdivide, i;

    for (i = 0; i < (int)ARRAY_SIZE(voxel_positions); i++)
        volume_set_at(volume, NULL, voxel_positions[i],
                      colors[i % ARRAY_SIZE(colors)]);
    accel = gpu_accel_create(GPU_ACCEL_VALIDATION);
    for (i = 0; i < (int)ARRAY_SIZE(tile_positions); i++) {
        count = volume_generate_vertices(
                volume, tile_positions[i],
                EFFECT_MARCHING_CUBES | EFFECT_MC_SMOOTH,
                vertices, &size, &subdivide);
        TEST(count > 0);
        TEST(size == 3);
        TEST(subdivide == 8);
        if (accel && gpu_accel_get_capabilities(accel)->available)
            TEST(gpu_accel_validate_mc_vertices(
                    accel, volume, tile_positions[i], vertices, count));
    }
    gpu_accel_destroy(accel);
    free(vertices);
    volume_delete(volume);
#endif
}

static void test_gpu_path_preview(void)
{
#ifdef __APPLE__
    volume_t *volume = volume_new();
    gpu_accel_t *accel;
    gpu_path_preview_params_t params = {
        .width = 8,
        .height = 8,
        .sample = 0,
        .max_steps = 64,
        .light_direction = {0, 0, -1, 0},
        .background = {0, 0, 0, 1},
        .light_intensity = 1,
        .ambient = 0.2,
    };
    uint8_t rgba[8 * 8 * 4] = {};
    const uint8_t voxel[4] = {220, 80, 40, 255};
    const int voxel_pos[3] = {-1, 0, 0};
    int i;

    for (i = 0; i < 4; i++) {
        params.ray_origins[i][0] = -0.5;
        params.ray_origins[i][1] = 0.5;
        params.ray_origins[i][2] = -4;
        params.ray_directions[i][2] = 1;
    }
    volume_set_at(volume, NULL, voxel_pos, voxel);
    accel = gpu_accel_create(GPU_ACCEL_VALIDATION);
    if (accel && gpu_accel_get_capabilities(accel)->pathtrace_preview) {
        TEST(gpu_accel_render_path_preview(
                accel, volume, &params, rgba));
        TEST(rgba[0] > rgba[1]);
        TEST(rgba[1] > rgba[2]);
        TEST(rgba[3] == 255);
    }
    gpu_accel_destroy(accel);
    volume_delete(volume);
#endif
}

void tests_run(void)
{
    test_load_file_v2();
    test_load_file_v1_with_preview();
    test_load_corrupt();
    test_xcom_swatches_file_roundtrip();
    test_gpu_accel_safety_helpers();
    test_gpu_marching_cubes_parity();
    test_gpu_path_preview();
}
